// Minimal client for the Jiten API.
//
// The live API is served from api.jiten.moe (NOT jiten.moe, which is the web
// frontend and 404s the /api routes). Its CORS policy allows any localhost
// origin, so this works from the Vite dev server without running the backend
// locally. Override with a `?api=` query param
// (e.g. `?api=https://localhost:7299/api`) to point at a local Jiten.Api.
const DEFAULT_API_BASE = location.hostname === "localhost" || location.hostname === "127.0.0.1"
    ? "https://api.jiten.moe/api"
    : "/api";
export function apiBase() {
    const override = new URLSearchParams(location.search).get("api");
    return (override ?? DEFAULT_API_BASE).replace(/\/+$/, "");
}
export const MEDIA_TYPES = [
    { id: 1, label: "Anime" },
    { id: 2, label: "Drama" },
    { id: 3, label: "Movie" },
    { id: 4, label: "Novel" },
    { id: 5, label: "Non-Fiction" },
    { id: 6, label: "Video Game" },
    { id: 7, label: "Visual Novel" },
    { id: 8, label: "Web Novel" },
    { id: 9, label: "Manga" },
    { id: 10, label: "Audio" },
];
const MEDIA_TYPE_LABELS = Object.fromEntries(MEDIA_TYPES.map(({ id, label }) => [id, label]));
export function mediaTypeLabel(mediaType) {
    return MEDIA_TYPE_LABELS[mediaType] ?? "Unknown";
}
export const PAGE_SIZE = 25;
/** Fetch one page of media decks, optionally filtered by `query` and/or `mediaType`. */
export async function fetchDecks(query = "", page = 1, mediaType) {
    const params = new URLSearchParams();
    if (query)
        params.set("titleFilter", query);
    if (mediaType !== undefined)
        params.set("mediaType", String(mediaType));
    params.set("offset", String((page - 1) * PAGE_SIZE));
    const res = await fetch(`${apiBase()}/media-deck/get-media-decks?${params}`, {
        headers: { Accept: "application/json" },
    });
    if (!res.ok) {
        throw new Error(`Failed to fetch decks (HTTP ${res.status})`);
    }
    const body = (await res.json());
    const decks = (body.data ?? []).slice(0, PAGE_SIZE);
    const hasMore = page * PAGE_SIZE < body.totalItems;
    return { decks, hasMore };
}
/**
 * Download a deck's Yomitan frequency dictionary.
 *
 * The per-deck Yomitan dictionary is generated by
 * `POST /api/media-deck/{id}/download` with `{ format: DeckFormat.Yomitan }`
 * (DeckFormat.Yomitan === 5), so it cannot be a plain `<a href>` link — the
 * request body is required. Returns the resulting zip as a Blob.
 */
export async function fetchDeckYomitanZip(deck) {
    const res = await fetch(`${apiBase()}/media-deck/${deck.deckId}/download`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ format: 5 /* DeckFormat.Yomitan */ }),
    });
    if (!res.ok) {
        throw new Error(`Failed to download (HTTP ${res.status})`);
    }
    return res.blob();
}
/** Best human-readable title for a deck. */
export function deckTitle(deck) {
    return deck.originalTitle || deck.englishTitle || deck.romajiTitle || `Deck ${deck.deckId}`;
}
