// Minimal client for the Jiten API.
//
// The live API is served from api.jiten.moe (NOT jiten.moe, which is the web
// frontend and 404s the /api routes). Its CORS policy allows any localhost
// origin, so this works from the Vite dev server without running the backend
// locally. Override with a `?api=` query param
// (e.g. `?api=https://localhost:7299/api`) to point at a local Jiten.Api.
const DEFAULT_API_BASE = location.hostname === "localhost" || location.hostname === "127.0.0.1"
    ? "https://api.jiten.moe/api"
    : "/api";
export function apiBase() {
    const override = new URLSearchParams(location.search).get("api");
    return (override ?? DEFAULT_API_BASE).replace(/\/+$/, "");
}
export const MEDIA_TYPES = [
    { id: 1, label: "Anime" },
    { id: 2, label: "Drama" },
    { id: 3, label: "Movie" },
    { id: 4, label: "Novel" },
    { id: 5, label: "Non-Fiction" },
    { id: 6, label: "Video Game" },
    { id: 7, label: "Visual Novel" },
    { id: 8, label: "Web Novel" },
    { id: 9, label: "Manga" },
    { id: 10, label: "Audio" },
];
const MEDIA_TYPE_LABELS = Object.fromEntries(MEDIA_TYPES.map(({ id, label }) => [id, label]));
export function mediaTypeLabel(mediaType) {
    return MEDIA_TYPE_LABELS[mediaType] ?? "Unknown";
}
export const PAGE_SIZE = 25;
/** Fetch one page of media decks, optionally filtered by `query` and/or `mediaType`. */
export async function fetchDecks(query = "", page = 1, mediaType) {
    const params = new URLSearchParams();
    if (query)
        params.set("titleFilter", query);
    if (mediaType !== undefined)
        params.set("mediaType", String(mediaType));
    params.set("offset", String((page - 1) * PAGE_SIZE));
    const res = await fetch(`${apiBase()}/media-deck/get-media-decks?${params}`, {
        headers: { Accept: "application/json" },
    });
    if (!res.ok) {
        throw new Error(`Failed to fetch decks (HTTP ${res.status})`);
    }
    const body = (await res.json());
    const decks = (body.data ?? []).slice(0, PAGE_SIZE);
    const hasMore = page * PAGE_SIZE < body.totalItems;
    return { decks, hasMore };
}
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
// Status codes worth retrying: rate limit + transient server/gateway errors.
const RETRYABLE = new Set([429, 500, 502, 503, 504]);
/**
 * Download a deck's Yomitan frequency dictionary.
 *
 * The per-deck Yomitan dictionary is generated by
 * `POST /api/media-deck/{id}/download` with `{ format: DeckFormat.Yomitan }`
 * (DeckFormat.Yomitan === 5), so it cannot be a plain `<a href>` link — the
 * request body is required. Returns the resulting zip as a Blob.
 *
 * The endpoint rate-limits under bursty load, so this retries on 429/5xx with
 * exponential backoff, honoring the `Retry-After` header when present.
 */
export async function fetchDeckYomitanZip(deck, attempts = 5) {
    for (let attempt = 1;; attempt++) {
        let res;
        try {
            res = await fetch(`${apiBase()}/media-deck/${deck.deckId}/download`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ format: 5 /* DeckFormat.Yomitan */ }),
            });
        }
        catch (err) {
            // Network error / connection reset — retry like a transient failure.
            if (attempt >= attempts)
                throw err;
            await sleep(backoffMs(attempt));
            continue;
        }
        if (res.ok)
            return res.blob();
        if (RETRYABLE.has(res.status) && attempt < attempts) {
            const retryAfter = Number(res.headers.get("Retry-After"));
            const waitMs = Number.isFinite(retryAfter) && retryAfter > 0
                ? retryAfter * 1000
                : backoffMs(attempt);
            await sleep(waitMs);
            continue;
        }
        throw new Error(`Failed to download (HTTP ${res.status})`);
    }
}
// 1s, 2s, 4s, 8s … capped at 15s, with jitter to avoid thundering herd.
function backoffMs(attempt) {
    return Math.min(2 ** (attempt - 1) * 1000, 15000) + Math.random() * 500;
}
/**
 * Map over `items` running at most `limit` async tasks at once, preserving
 * input order in the result. Stops and rejects on the first task that throws
 * after its own retries are exhausted. `onProgress` fires as each item settles.
 */
export async function mapPool(items, limit, fn, onProgress) {
    const results = new Array(items.length);
    let next = 0;
    let done = 0;
    async function worker() {
        while (next < items.length) {
            const i = next++;
            results[i] = await fn(items[i], i);
            done++;
            onProgress?.(done, items.length);
        }
    }
    const workers = Array.from({ length: Math.min(limit, items.length) }, worker);
    await Promise.all(workers);
    return results;
}
/** Best human-readable title for a deck. */
export function deckTitle(deck) {
    return deck.originalTitle || deck.englishTitle || deck.romajiTitle || `Deck ${deck.deckId}`;
}
