// Minimal client for the Jiten API.
//
// The live API is served from api.jiten.moe (NOT jiten.moe, which is the web
// frontend and 404s the /api routes). Its CORS policy allows any localhost
// origin, so this works from the Vite dev server without running the backend
// locally. Override with a `?api=` query param
// (e.g. `?api=https://localhost:7299/api`) to point at a local Jiten.Api.
const DEFAULT_API_BASE = "https://api.jiten.moe/api";
export function apiBase() {
    const override = new URLSearchParams(location.search).get("api");
    return (override ?? DEFAULT_API_BASE).replace(/\/+$/, "");
}
const MEDIA_TYPE_LABELS = {
    1: "Anime",
    2: "Drama",
    3: "Movie",
    4: "Novel",
    5: "Non-Fiction",
    6: "Video Game",
    7: "Visual Novel",
    8: "Web Novel",
    9: "Manga",
    10: "Audio",
};
export function mediaTypeLabel(mediaType) {
    return MEDIA_TYPE_LABELS[mediaType] ?? "Unknown";
}
/** Fetch the first `limit` media decks from the Jiten API. */
export async function fetchDecks(limit = 10) {
    const res = await fetch(`${apiBase()}/media-deck/get-media-decks`, {
        headers: { Accept: "application/json" },
    });
    if (!res.ok) {
        throw new Error(`Failed to fetch decks (HTTP ${res.status})`);
    }
    const body = (await res.json());
    return (body.data ?? []).slice(0, limit);
}
/**
 * Download a deck's Yomitan frequency dictionary.
 *
 * The per-deck Yomitan dictionary is generated by
 * `POST /api/media-deck/{id}/download` with `{ format: DeckFormat.Yomitan }`
 * (DeckFormat.Yomitan === 5), so it cannot be a plain `<a href>` link — the
 * request body is required. Returns the resulting zip as a Blob.
 */
export async function fetchDeckYomitanZip(deck) {
    const res = await fetch(`${apiBase()}/media-deck/${deck.deckId}/download`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ format: 5 /* DeckFormat.Yomitan */ }),
    });
    if (!res.ok) {
        throw new Error(`Failed to download (HTTP ${res.status})`);
    }
    return res.blob();
}
/** Best human-readable title for a deck. */
export function deckTitle(deck) {
    return deck.originalTitle || deck.englishTitle || deck.romajiTitle || `Deck ${deck.deckId}`;
}
